# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-20 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Olu\u015fturma Tarihi')),
                ('import_edildi', models.BooleanField(default=False, verbose_name="Dspace'e Aktar\u0131ld\u0131")),
                ('import_edilme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name="Dspace'e Aktar\u0131lma Zaman\u0131")),
            ],
            options={
                'ordering': ('import_edildi',),
                'verbose_name': "Dspace'e Aktarma Dosyas\u0131",
                'verbose_name_plural': "Dspace'e Aktarma Dosyalar\u0131",
            },
        ),
        migrations.CreateModel(
            name='Dergi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dergi_adi', models.CharField(max_length=150, verbose_name='Dergi Ad\u0131')),
                ('oai_url', models.CharField(default='https://dergipark.org.tr/api/public/oai/', max_length=200, verbose_name='OAI URL')),
                ('set_name', models.CharField(max_length=50, verbose_name='Set Ad\u0131')),
                ('issn', models.CharField(blank=True, max_length=9, verbose_name='ISSN')),
                ('son_calisma', models.DateTimeField(blank=True, null=True, verbose_name='Son \xc7al\u0131\u015fma Zaman\u0131')),
            ],
            options={
                'verbose_name': 'Dergi',
                'verbose_name_plural': 'Dergiler',
            },
        ),
        migrations.CreateModel(
            name='DergiSet',
            fields=[
                ('set_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Set ID')),
                ('set_name', models.CharField(max_length=50, verbose_name='Set Ad\u0131')),
                ('import_to_dspace', models.BooleanField(default=False, verbose_name="Dspace'e aktar")),
                ('dergi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='dergipark.Dergi', verbose_name='Dergi')),
            ],
            options={
                'ordering': ('dergi',),
                'verbose_name': 'Dergi Alt Seti',
                'verbose_name_plural': 'Dergi Alt Setleri',
            },
        ),
        migrations.CreateModel(
            name='Dosya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=150, verbose_name='Dosya Adresi')),
                ('mimetype', models.CharField(blank=True, max_length=50, verbose_name='Dosya Tipi')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='makaleler')),
                ('size', models.PositiveIntegerField(default=0, editable=False, verbose_name='Dosya Boyutu')),
            ],
            options={
                'verbose_name': 'Dosya',
                'verbose_name_plural': 'Dosyalar',
            },
        ),
        migrations.CreateModel(
            name='Makale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=150, unique=True, verbose_name='OAI Identifier')),
                ('datestamp', models.DateField(blank=True, null=True, verbose_name='Datestamp')),
                ('title_tr', models.CharField(blank=True, max_length=250, verbose_name='Ba\u015fl\u0131k [TR]')),
                ('title_en', models.CharField(blank=True, max_length=250, verbose_name='Ba\u015fl\u0131k [EN]')),
                ('description_tr', models.TextField(blank=True, null=True, verbose_name='A\xe7\u0131klama [TR]')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='A\xe7\u0131klama [EN]')),
                ('subject_tr', models.CharField(blank=True, max_length=250, verbose_name='Anahtar Kelimeler [TR]')),
                ('subject_en', models.CharField(blank=True, max_length=250, verbose_name='Anahtar Kelimeler [EN]')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='Dil')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='Yay\u0131nc\u0131')),
                ('batchimport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dergipark.BatchImport', verbose_name="Dspace'e Aktarma Dosyas\u0131")),
                ('dergi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dergipark.Dergi')),
                ('dergi_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dergipark.DergiSet', verbose_name='DergiSet')),
            ],
            options={
                'verbose_name': 'Makale',
                'verbose_name_plural': 'Makaleler',
            },
        ),
        migrations.CreateModel(
            name='Yazar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazar_adi', models.CharField(max_length=150, verbose_name='Yazar Ad\u0131')),
                ('cleaned_yazar_adi', models.CharField(blank=True, max_length=150, verbose_name='Yazar Ad\u0131 (Dspace)')),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dergipark.Makale', verbose_name='Makale')),
            ],
            options={
                'verbose_name': 'Yazar',
                'verbose_name_plural': 'Yazarlar',
            },
        ),
        migrations.AddField(
            model_name='dosya',
            name='makale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dergipark.Makale', verbose_name='Makale'),
        ),
        migrations.AlterUniqueTogether(
            name='dergi',
            unique_together=set([('oai_url', 'set_name')]),
        ),
        migrations.AddField(
            model_name='batchimport',
            name='dergi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dergipark.Dergi', verbose_name='Dergi'),
        ),
    ]
