# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-29 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dergipark', '0002_auto_20191129_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosya',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to='makaleler'),
        ),
    ]
