# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dergipark', '0003_dosya_dosya'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosya',
            name='mimetype',
            field=models.CharField(blank=True, max_length=50, verbose_name='Dosya Tipi'),
        ),
    ]
