# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dergipark', '0004_dosya_mimetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='dergi',
            name='son_calisma',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son \xc7al\u0131\u015fma Zaman\u0131'),
        ),
    ]
