# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-03 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dergipark', '0005_dergi_son_calisma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sayi',
            options={'ordering': ('dergi', 'yil', 'cilt_no', 'sayi_no'), 'verbose_name': 'Say\u0131', 'verbose_name_plural': 'Say\u0131lar'},
        ),
        migrations.AddField(
            model_name='sayi',
            name='yil',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Y\u0131l'),
        ),
        migrations.AlterField(
            model_name='sayi',
            name='cilt_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cilt No'),
        ),
        migrations.AlterField(
            model_name='sayi',
            name='sayi_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Say\u0131 No'),
        ),
        migrations.AlterUniqueTogether(
            name='sayi',
            unique_together=set([]),
        ),
    ]
