# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-03 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dergipark', '0006_auto_20191203_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Olu\u015fturma Tarihi')),
                ('import_edildi', models.BooleanField(default=False, verbose_name="Dspace'e Aktar\u0131ld\u0131")),
                ('import_edilme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name="Dspace'e Aktar\u0131lma Zaman\u0131")),
                ('dergi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dergipark.Dergi', verbose_name='Dergi')),
            ],
            options={
                'verbose_name': "Dspace'e Aktarma Dosyas\u0131",
                'verbose_name_plural': "Dspace'e Aktarma Dosyalar\u0131",
            },
        ),
        migrations.AlterField(
            model_name='makale',
            name='dergi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dergipark.Dergi'),
        ),
        migrations.AddField(
            model_name='makale',
            name='batchimport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dergipark.BatchImport', verbose_name="Dspace'e Aktarma Dosyas\u0131"),
        ),
    ]
