# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-03 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dergipark', '0007_auto_20191203_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sayi',
            name='dergi',
        ),
        migrations.RemoveField(
            model_name='makale',
            name='sayi',
        ),
        migrations.DeleteModel(
            name='Sayi',
        ),
    ]
