# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-17 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dergipark', '0009_dosya_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazar',
            name='yazar_adi_clean',
            field=models.CharField(blank=True, max_length=150, verbose_name='Yazar Ad\u0131 (Dspace)'),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='yazar_adi',
            field=models.CharField(max_length=150, verbose_name='Yazar Ad\u0131'),
        ),
    ]
