# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-19 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dergipark', '0010_auto_20191217_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yazar',
            old_name='yazar_adi_clean',
            new_name='cleaned_yazar_adi',
        ),
    ]
